# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-07 06:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design6', '0002_auto_20180102_2250'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='image',
            field=models.ImageField(default='gallery/None/no-img.jpg', upload_to='gallery/'),
        ),
    ]
