# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-18 02:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design6', '0003_gallery_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='title', max_length=250),
        ),
    ]
