# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-18 17:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design6', '0006_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.ImageField(default='gallery/None/no-img.jpg', upload_to='gallery/%Y/%m/%d'),
        ),
    ]
