# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-26 08:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design6', '0007_auto_20180118_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.ImageField(default='gallery/None/no-img.jpg', upload_to='users/%Y/%m/%d'),
        ),
    ]
