# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-26 08:22
from __future__ import unicode_literals

import design6.imageUpload
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design6', '0009_auto_20180126_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to=design6.imageUpload.get_upload_path),
        ),
    ]
